spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:dev_db?reWriteBatchedInserts=true"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 40
        order_inserts: true